Write a Python Program to Add Two Matrices?

In [13]:
Mat1 =[[1,2,3],[4,5,6],[7,8,9]]
Mat2 =[[9,8,7],[6,5,4],[3,2,1]]
sum  =[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(Mat1)):
    for j in range(len(Mat1[0])):
        sum[i][j]=Mat1[i][j]+Mat2[i][j]
print(sum)

[[10, 10, 10], [10, 10, 10], [10, 10, 10]]


Write a Python Program to Multiply Two Matrices?


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,0,0],[0,1,0],[0,0,1]])
mul=[[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(mul)):
            mul[i][j] += a[i][k] * b[k][j]
print(f'addition of 2 matrices is \n{a+b}')
print(f'addition of 2 matrices is \n{mul}')


addition of 2 matrices is 
[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
addition of 2 matrices is 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Write a Python Program to Transpose a Matrix?


In [34]:
Mat1 =[[1,2,3,4],[4,5,6,10],[7,8,9,11]]
Mat2 =[[0,0,0],[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(Mat1)):
    for j in range(len(Mat1[0])):
        Mat2[j][i]=Mat1[i][j]
        
print(Mat2)

[[1, 4, 7], [2, 5, 8], [3, 6, 9], [4, 10, 11]]


Write a Python Program to Sort Words in Alphabetic Order?


In [43]:
def sort_words(arr):
    lst=[i.upper() for i in arr]
    lst.sort()
    print(lst)
sort_words(['cat','apple','zoo','Amazon','TCS'])

['AMAZON', 'APPLE', 'CAT', 'TCS', 'ZOO']


Write a Python Program to Remove Punctuation From a String?

In [49]:
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
def remove_punc(str):
    for i in str:
        if i in punc:
            str=str.replace(i,'')
    return str
remove_punc('sa;sdhb,.sdfg')

'sasdhbsdfg'